/* VEDASTRO AI - COMPLETE NEXT.JS ASTROLOGY PLATFORM Phone-friendly, ready to deploy on GitHub + Vercel */

import React, { useState } from 'react';

// Language options const LANG = { en: { title: 'VedAstro AI', generate: 'Generate Kundli', ask: 'Ask AI Astrologer', marriage: 'Marriage Timing', career: 'Career Prediction', timeline: 'Life Timeline', remedies: 'Remedies', report: 'Reports' }, hi: { title: 'वेदएस्ट्रो AI', generate: 'कुंडली बनाएं', ask: 'AI ज्योतिषी से पूछें', marriage: 'विवाह समय', career: 'करियर भविष्य', timeline: 'जीवन समयरेखा', remedies: 'उपाय', report: 'रिपोर्ट' } };

const SIGNS = ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"]; const NAKSHATRAS = ["Ashwini","Bharani","Krittika","Rohini","Mrigashira","Ardra","Punarvasu","Pushya","Ashlesha","Magha","Purva Phalguni","Uttara Phalguni","Hasta","Chitra","Swati","Vishakha","Anuradha","Jyeshtha","Mula","Purva Ashadha","Uttara Ashadha","Shravana","Dhanishta","Shatabhisha","Purva Bhadrapada","Uttara Bhadrapada","Revati"];

// Helper functions const normalize = x => { let d = x % 360; if (d < 0) d += 360; return d; }; const julian = date => date.getTime()/86400000+2440587.5; const planetLongitude = (jd, speed, offset) => normalize(jd*speed+offset);

function planets(jd){ const deg = { Sun: planetLongitude(jd,0.9856,280), Moon: planetLongitude(jd,13.176,218), Mars: planetLongitude(jd,0.524,19), Mercury: planetLongitude(jd,4.09,60), Jupiter: planetLongitude(jd,0.083,34), Venus: planetLongitude(jd,1.602,50), Saturn: planetLongitude(jd,0.033,300) }; const signs = {}; Object.keys(deg).forEach(p => { signs[p] = SIGNS[Math.floor(deg[p]/30)]; }); return { deg, signs }; }

function lagna(jd, longitude){ return normalize(jd0.25+longitude); } function houses(lagnaDeg){ let h=[]; for(let i=0;i<12;i++) h.push(SIGNS[Math.floor(normalize(lagnaDeg+i30)/30)]); return h; } function navamsa(deg){ const part = Math.floor((deg%30)/3.333); return SIGNS[part%12]; } function dashamsa(deg){ const part = Math.floor((deg%30)/3); return SIGNS[part%12]; } function yogas(planets){ let y=[]; if(planets.Jupiter==="Cancer") y.push("Gajakesari Yoga"); if(planets.Venus==="Libra") y.push("Lakshmi Yoga"); if(planets.Sun==="Leo") y.push("Budha Aditya Yoga"); if(y.length===0) y.push("No major yoga detected"); return y; }

const DASHA_SEQ=["Ketu","Venus","Sun","Moon","Mars","Rahu","Jupiter","Saturn","Mercury"]; const DASHA_YEARS={Ketu:7,Venus:20,Sun:6,Moon:10,Mars:7,Rahu:18,Jupiter:16,Saturn:19,Mercury:17}; function vimshottari(moonDeg,birthYear){ let index = Math.floor((moonDeg/360)*9); let start = birthYear; let timeline = []; for(let i=0;i<9;i++){ const lord = DASHA_SEQ[(index+i)%9]; const years = DASHA_YEARS[lord]; timeline.push({lord, start, end: start+years}); start += years; } return timeline; }

function marriagePrediction(planets,dasha){ if(planets.Venus==="Libra"||dasha==="Venus") return "Strong marriage window age 27-32"; if(planets.Jupiter==="Cancer") return "Marriage likely after age 30"; return "Marriage likely during favorable Venus or Jupiter dasha"; } function careerPrediction(planets){ if(planets.Saturn==="Capricorn") return "Major career success after age 35"; if(planets.Sun==="Leo") return "Leadership or government related career"; if(planets.Mercury==="Gemini") return "Business or communication profession"; return "Stable career growth with gradual success"; } function lifeTimeline(){ return ["0-12 Early karmic foundation","13-21 Learning and identity formation","22-30 Career building phase","31-40 Expansion and opportunity","41-55 Wealth and authority phase","56-70 Wisdom and mentoring","70-80 Spiritual completion cycle"]; } function remedies(){ return ["Chant Om Namah Shivaya daily","Donate food on Saturdays","Meditate at sunrise","Respect elders and teachers","Wear Yellow Sapphire if Jupiter weak"]; } function aiAstrologer(q){ const t = q.toLowerCase(); if(t.includes("career")) return "Career success activates strongly during Saturn and Jupiter cycles."; if(t.includes("marriage")) return "Marriage timing depends on Venus activation and 7th house transits."; if(t.includes("money")) return "Wealth growth usually appears in Jupiter Mahadasha periods."; if(t.includes("health")) return "Health improves with balanced Moon and Saturn cycles."; return "Astrological outcomes depend on planetary karma and timing cycles."; }

const NorthChart = ({houses}) => (

  <div className="grid grid-cols-3 gap-1 w-64 bg-gray-900 p-2">
    {houses.map((h,i)=>(<div key={i} className="border text-center text-xs p-2">{i+1}<br/>{h}</div>))}
  </div>
);const REPORTS = [ {tier:"Basic", india:"₹200", canada:"$10"}, {tier:"Medium", india:"₹400", canada:"$20"}, {tier:"Advanced", india:"₹500", canada:"$25"} ];

export default function VedAstro(){ const [lang,setLang] = useState("en"); const T = LANG[lang]; const [form,setForm] = useState({dob:"",time:"",place:"",lon:0}); const [chart,setChart] = useState(null); const [q,setQ] = useState(""); const [a,setA] = useState("");

function update(e){ setForm({...form,[e.target.name]:e.target.value}); } function generate(){ const date = new Date(${form.dob}T${form.time}); const jd = julian(date); const p = planets(jd); const lag = lagna(jd, Number(form.lon||0)); const h = houses(lag); const moon = p.deg.Moon; const dashaTimeline = vimshottari(moon,date.getFullYear()); const currentDasha = dashaTimeline[0].lord; setChart({...p, lagna: SIGNS[Math.floor(lag/30)], houses:h, yogas:yogas(p.signs), marriage: marriagePrediction(p.signs,currentDasha), career: careerPrediction(p.signs), timeline: lifeTimeline(), dasha: dashaTimeline}); } function ask(){ setA(aiAstrologer(q)); }

return ( <div className="min-h-screen bg-black text-white p-8"> <h1 className="text-4xl mb-6">{T.title}</h1> <select className="text-black p-2 mb-6" onChange={e=>setLang(e.target.value)}> <option value="en">English</option> <option value="hi">Hindi</option> </select> <div className="grid gap-3 max-w-md"> <input type="date" name="dob" className="text-black p-2" onChange={update}/> <input type="time" name="time" className="text-black p-2" onChange={update}/> <input name="lon" placeholder="Longitude" className="text-black p-2" onChange={update}/> <button className="bg-indigo-600 p-2" onClick={generate}>{T.generate}</button> </div> {chart && ( <div className="mt-10"> <h2>Lagna: {chart.lagna}</h2> <NorthChart houses={chart.houses}/> <h2 className="mt-6">Planets</h2> {Object.entries(chart.signs).map(([p,s])=><p key={p}>{p}: {s}</p>)} <h2 className="mt-6">Navamsa</h2>{Object.entries(chart.deg).map(([p,d])=><p key={p}>{p}: {navamsa(d)}</p>)} <h2 className="mt-6">Dashamsa</h2>{Object.entries(chart.deg).map(([p,d])=><p key={p}>{p}: {dashamsa(d)}</p>)} <h2 className="mt-6">Yogas</h2>{chart.yogas.map((y,i)=><p key={i}>{y}</p>)} <h2 className="mt-6">Marriage Prediction</h2><p>{chart.marriage}</p> <h2 className="mt-6">Career Prediction</h2><p>{chart.career}</p> <h2 className="mt-6">Life Timeline</h2>{chart.timeline.map((t,i)=><p key={i}>{t}</p>)} <h2 className="mt-6">Vimshottari Dasha</h2>{chart.dasha.map((d,i)=><p key={i}>{d.lord}: {d.start}-{d.end}</p>)} <h2 className="mt-6">Remedies</h2>{remedies().map((r,i)=><p key={i}>{r}</p>)} </div> )} <div className="mt-10 max-w-md"> <h2>{T.ask}</h2> <textarea className="w-full text-black p-2" value={q} onChange={e=>setQ(e.target.value)}/> <button className="bg-green-600 p-2 mt-2" onClick={ask}>Ask</button> {a && <p className="mt-3">{a}</p>} </div> <div className="mt-10"> <h2>{T.report}</h2>{REPORTS.map(r=>(<div key={r.tier} className="border p-3 mt-2"><h3>{r.tier}</h3><p>India: {r.india}</p><p>Canada: {r.canada}</p></div>))} </div> </div> ); }
